version: 1
collections:
  - collection: bookhunt_books
    meta:
      collection: bookhunt_books
      icon: auto_stories
      note: Catalog of books managed by Bookhunt.
      display_template: "{{title}}"
      sort_field: title
      hidden: false
      singleton: false
    schema:
      name: bookhunt_books
      comment: Catalog of books managed by Bookhunt.
      schema: public
fields:
  - collection: bookhunt_books
    field: id
    type: uuid
    schema:
      name: id
      table: bookhunt_books
      data_type: uuid
      default_value: gen_random_uuid()
      is_nullable: false
      is_primary_key: true
    meta:
      interface: input
      special:
        - uuid
      readonly: true
      hidden: true
  - collection: bookhunt_books
    field: status
    type: string
    schema:
      name: status
      table: bookhunt_books
      data_type: character varying
      max_length: 50
      default_value: draft
      is_nullable: false
    meta:
      interface: select-dropdown
      special:
        - status
      options:
        choices:
          - text: Draft
            value: draft
          - text: Published
            value: published
          - text: Archived
            value: archived
  - collection: bookhunt_books
    field: title
    type: text
    schema:
      name: title
      table: bookhunt_books
      data_type: text
      is_nullable: false
    meta:
      interface: input
      options:
        placeholder: "Book title"
  - collection: bookhunt_books
    field: author
    type: text
    schema:
      name: author
      table: bookhunt_books
      data_type: text
      is_nullable: true
    meta:
      interface: input
      options:
        placeholder: "Author"
  - collection: bookhunt_books
    field: description
    type: text
    schema:
      name: description
      table: bookhunt_books
      data_type: text
      is_nullable: true
    meta:
      interface: input-rich-text-md
      options:
        toolbar:
          - bold
          - italic
          - link
          - bullet
  - collection: bookhunt_books
    field: cover_url
    type: text
    schema:
      name: cover_url
      table: bookhunt_books
      data_type: text
      is_nullable: true
    meta:
      interface: input
      options:
        placeholder: "https://"
  - collection: bookhunt_books
    field: published_year
    type: integer
    schema:
      name: published_year
      table: bookhunt_books
      data_type: integer
      is_nullable: true
    meta:
      interface: input
      options:
        placeholder: "2024"
  - collection: bookhunt_books
    field: created_at
    type: timestamp
    schema:
      name: created_at
      table: bookhunt_books
      data_type: timestamp with time zone
      default_value: now()
      is_nullable: false
    meta:
      interface: datetime
      special:
        - date-created
      readonly: true
  - collection: bookhunt_books
    field: updated_at
    type: timestamp
    schema:
      name: updated_at
      table: bookhunt_books
      data_type: timestamp with time zone
      default_value: now()
      is_nullable: false
    meta:
      interface: datetime
      special:
        - date-updated
      readonly: true
